server:
  port: 9602


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: xuxin

#  redis:
#    host: 192.168.6.222
#    port: 6379
#    timeout: 1000
#    database: 0
#    password: 123456
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 3
#        max-wait: -1
#        min-idle: 0

#配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*Mapper.xml

